// Generated by @moks/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({ list: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint3_0Input = { readonly location?: Endpoint3_0Request["query"]["location"] }
const Endpoint3_0 = (raw: RawClient["server.model"]) => (input?: Endpoint3_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup3 = (raw: RawClient["server.model"]) => ({ list: Endpoint3_0(raw) })

type Endpoint4_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint4_0Input = { readonly location?: Endpoint4_0Request["query"]["location"] }
const Endpoint4_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint4_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint4_1Input = {
  readonly providerID: Endpoint4_1Request["params"]["providerID"]
  readonly location?: Endpoint4_1Request["query"]["location"]
}
const Endpoint4_1 = (raw: RawClient["server.provider"]) => (input: Endpoint4_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup4 = (raw: RawClient["server.provider"]) => ({ list: Endpoint4_0(raw), get: Endpoint4_1(raw) })

type Endpoint5_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint5_0Input = { readonly location?: Endpoint5_0Request["query"]["location"] }
const Endpoint5_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint5_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint5_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint5_1Input = {
  readonly integrationID: Endpoint5_1Request["params"]["integrationID"]
  readonly location?: Endpoint5_1Request["query"]["location"]
}
const Endpoint5_1 = (raw: RawClient["server.integration"]) => (input: Endpoint5_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint5_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint5_2Input = {
  readonly integrationID: Endpoint5_2Request["params"]["integrationID"]
  readonly location?: Endpoint5_2Request["query"]["location"]
  readonly key: Endpoint5_2Request["payload"]["key"]
  readonly label?: Endpoint5_2Request["payload"]["label"]
}
const Endpoint5_2 = (raw: RawClient["server.integration"]) => (input: Endpoint5_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint5_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint5_3Input = {
  readonly integrationID: Endpoint5_3Request["params"]["integrationID"]
  readonly location?: Endpoint5_3Request["query"]["location"]
  readonly methodID: Endpoint5_3Request["payload"]["methodID"]
  readonly inputs: Endpoint5_3Request["payload"]["inputs"]
  readonly label?: Endpoint5_3Request["payload"]["label"]
}
const Endpoint5_3 = (raw: RawClient["server.integration"]) => (input: Endpoint5_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint5_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint5_4Input = {
  readonly attemptID: Endpoint5_4Request["params"]["attemptID"]
  readonly location?: Endpoint5_4Request["query"]["location"]
}
const Endpoint5_4 = (raw: RawClient["server.integration"]) => (input: Endpoint5_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint5_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint5_5Input = {
  readonly attemptID: Endpoint5_5Request["params"]["attemptID"]
  readonly location?: Endpoint5_5Request["query"]["location"]
  readonly code?: Endpoint5_5Request["payload"]["code"]
}
const Endpoint5_5 = (raw: RawClient["server.integration"]) => (input: Endpoint5_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint5_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint5_6Input = {
  readonly attemptID: Endpoint5_6Request["params"]["attemptID"]
  readonly location?: Endpoint5_6Request["query"]["location"]
}
const Endpoint5_6 = (raw: RawClient["server.integration"]) => (input: Endpoint5_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint5_0(raw),
  get: Endpoint5_1(raw),
  connectKey: Endpoint5_2(raw),
  connectOauth: Endpoint5_3(raw),
  attemptStatus: Endpoint5_4(raw),
  attemptComplete: Endpoint5_5(raw),
  attemptCancel: Endpoint5_6(raw),
})

type Endpoint6_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint6_0Input = {
  readonly credentialID: Endpoint6_0Request["params"]["credentialID"]
  readonly location?: Endpoint6_0Request["query"]["location"]
  readonly label: Endpoint6_0Request["payload"]["label"]
}
const Endpoint6_0 = (raw: RawClient["server.credential"]) => (input: Endpoint6_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint6_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint6_1Input = {
  readonly credentialID: Endpoint6_1Request["params"]["credentialID"]
  readonly location?: Endpoint6_1Request["query"]["location"]
}
const Endpoint6_1 = (raw: RawClient["server.credential"]) => (input: Endpoint6_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup6 = (raw: RawClient["server.credential"]) => ({ update: Endpoint6_0(raw), remove: Endpoint6_1(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint7_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint7_1Input = { readonly projectID?: Endpoint7_1Request["query"]["projectID"] }
const Endpoint7_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint7_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint7_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint7_2Input = { readonly id: Endpoint7_2Request["params"]["id"] }
const Endpoint7_2 = (raw: RawClient["server.permission"]) => (input: Endpoint7_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint7_3Input = {
  readonly sessionID: Endpoint7_3Request["params"]["sessionID"]
  readonly id?: Endpoint7_3Request["payload"]["id"]
  readonly action: Endpoint7_3Request["payload"]["action"]
  readonly resources: Endpoint7_3Request["payload"]["resources"]
  readonly save?: Endpoint7_3Request["payload"]["save"]
  readonly metadata?: Endpoint7_3Request["payload"]["metadata"]
  readonly source?: Endpoint7_3Request["payload"]["source"]
  readonly agent?: Endpoint7_3Request["payload"]["agent"]
}
const Endpoint7_3 = (raw: RawClient["server.permission"]) => (input: Endpoint7_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint7_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint7_4Input = { readonly sessionID: Endpoint7_4Request["params"]["sessionID"] }
const Endpoint7_4 = (raw: RawClient["server.permission"]) => (input: Endpoint7_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint7_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint7_5Input = {
  readonly sessionID: Endpoint7_5Request["params"]["sessionID"]
  readonly requestID: Endpoint7_5Request["params"]["requestID"]
}
const Endpoint7_5 = (raw: RawClient["server.permission"]) => (input: Endpoint7_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint7_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint7_6Input = {
  readonly sessionID: Endpoint7_6Request["params"]["sessionID"]
  readonly requestID: Endpoint7_6Request["params"]["requestID"]
  readonly reply: Endpoint7_6Request["payload"]["reply"]
  readonly message?: Endpoint7_6Request["payload"]["message"]
}
const Endpoint7_6 = (raw: RawClient["server.permission"]) => (input: Endpoint7_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint7_0(raw),
  listSaved: Endpoint7_1(raw),
  removeSaved: Endpoint7_2(raw),
  create: Endpoint7_3(raw),
  list: Endpoint7_4(raw),
  get: Endpoint7_5(raw),
  reply: Endpoint7_6(raw),
})

type Endpoint8_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint8_0Input = {
  readonly location?: Endpoint8_0Request["query"]["location"]
  readonly path?: Endpoint8_0Request["query"]["path"]
}
const Endpoint8_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint8_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint8_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint8_1Input = {
  readonly location?: Endpoint8_1Request["query"]["location"]
  readonly query: Endpoint8_1Request["query"]["query"]
  readonly type?: Endpoint8_1Request["query"]["type"]
  readonly limit?: Endpoint8_1Request["query"]["limit"]
}
const Endpoint8_1 = (raw: RawClient["server.fs"]) => (input: Endpoint8_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.fs"]) => ({ list: Endpoint8_0(raw), find: Endpoint8_1(raw) })

type Endpoint9_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint9_0Input = { readonly location?: Endpoint9_0Request["query"]["location"] }
const Endpoint9_0 = (raw: RawClient["server.command"]) => (input?: Endpoint9_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.command"]) => ({ list: Endpoint9_0(raw) })

type Endpoint10_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint10_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.skill"]) => ({ list: Endpoint10_0(raw) })

const Endpoint11_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup11 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint11_0(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint12_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint12_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint12_1Input = {
  readonly location?: Endpoint12_1Request["query"]["location"]
  readonly command?: Endpoint12_1Request["payload"]["command"]
  readonly args?: Endpoint12_1Request["payload"]["args"]
  readonly cwd?: Endpoint12_1Request["payload"]["cwd"]
  readonly title?: Endpoint12_1Request["payload"]["title"]
  readonly env?: Endpoint12_1Request["payload"]["env"]
}
const Endpoint12_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint12_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint12_2Input = {
  readonly ptyID: Endpoint12_2Request["params"]["ptyID"]
  readonly location?: Endpoint12_2Request["query"]["location"]
}
const Endpoint12_2 = (raw: RawClient["server.pty"]) => (input: Endpoint12_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint12_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint12_3Input = {
  readonly ptyID: Endpoint12_3Request["params"]["ptyID"]
  readonly location?: Endpoint12_3Request["query"]["location"]
  readonly title?: Endpoint12_3Request["payload"]["title"]
  readonly size?: Endpoint12_3Request["payload"]["size"]
}
const Endpoint12_3 = (raw: RawClient["server.pty"]) => (input: Endpoint12_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint12_4Input = {
  readonly ptyID: Endpoint12_4Request["params"]["ptyID"]
  readonly location?: Endpoint12_4Request["query"]["location"]
}
const Endpoint12_4 = (raw: RawClient["server.pty"]) => (input: Endpoint12_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup12 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint12_0(raw),
  create: Endpoint12_1(raw),
  get: Endpoint12_2(raw),
  update: Endpoint12_3(raw),
  remove: Endpoint12_4(raw),
})

type Endpoint13_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint13_0Input = { readonly location?: Endpoint13_0Request["query"]["location"] }
const Endpoint13_0 = (raw: RawClient["server.question"]) => (input?: Endpoint13_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint13_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint13_1Input = { readonly sessionID: Endpoint13_1Request["params"]["sessionID"] }
const Endpoint13_1 = (raw: RawClient["server.question"]) => (input: Endpoint13_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint13_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint13_2Input = {
  readonly sessionID: Endpoint13_2Request["params"]["sessionID"]
  readonly requestID: Endpoint13_2Request["params"]["requestID"]
  readonly answers: Endpoint13_2Request["payload"]["answers"]
}
const Endpoint13_2 = (raw: RawClient["server.question"]) => (input: Endpoint13_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint13_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint13_3Input = {
  readonly sessionID: Endpoint13_3Request["params"]["sessionID"]
  readonly requestID: Endpoint13_3Request["params"]["requestID"]
}
const Endpoint13_3 = (raw: RawClient["server.question"]) => (input: Endpoint13_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup13 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint13_0(raw),
  list: Endpoint13_1(raw),
  reply: Endpoint13_2(raw),
  reject: Endpoint13_3(raw),
})

type Endpoint14_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint14_0Input = { readonly location?: Endpoint14_0Request["query"]["location"] }
const Endpoint14_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint14_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup14 = (raw: RawClient["server.reference"]) => ({ list: Endpoint14_0(raw) })

type Endpoint15_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint15_0Input = {
  readonly projectID: Endpoint15_0Request["params"]["projectID"]
  readonly location?: Endpoint15_0Request["query"]["location"]
  readonly strategy: Endpoint15_0Request["payload"]["strategy"]
  readonly directory: Endpoint15_0Request["payload"]["directory"]
  readonly name?: Endpoint15_0Request["payload"]["name"]
}
const Endpoint15_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint15_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint15_1Input = {
  readonly projectID: Endpoint15_1Request["params"]["projectID"]
  readonly location?: Endpoint15_1Request["query"]["location"]
  readonly directory: Endpoint15_1Request["payload"]["directory"]
  readonly force: Endpoint15_1Request["payload"]["force"]
}
const Endpoint15_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint15_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint15_2Input = {
  readonly projectID: Endpoint15_2Request["params"]["projectID"]
  readonly location?: Endpoint15_2Request["query"]["location"]
}
const Endpoint15_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint15_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup15 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint15_0(raw),
  remove: Endpoint15_1(raw),
  refresh: Endpoint15_2(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  models: adaptGroup3(raw["server.model"]),
  providers: adaptGroup4(raw["server.provider"]),
  integrations: adaptGroup5(raw["server.integration"]),
  credentials: adaptGroup6(raw["server.credential"]),
  permissions: adaptGroup7(raw["server.permission"]),
  files: adaptGroup8(raw["server.fs"]),
  commands: adaptGroup9(raw["server.command"]),
  skills: adaptGroup10(raw["server.skill"]),
  events: adaptGroup11(raw["server.event"]),
  ptys: adaptGroup12(raw["server.pty"]),
  questions: adaptGroup13(raw["server.question"]),
  references: adaptGroup14(raw["server.reference"]),
  projectCopies: adaptGroup15(raw["server.projectCopy"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
